-- BORRADO DE OBJETOS A CONSTRUIR --
DROP TABLE VIA_ADMIN CASCADE CONSTRAINTS;
DROP TABLE TIPO_MED CASCADE CONSTRAINTS;
DROP TABLE DOSIS CASCADE CONSTRAINTS;
DROP TABLE MEDICAMENTO CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE DIGITADOR CASCADE CONSTRAINTS;
DROP TABLE BANCO CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSTICO CASCADE CONSTRAINTS;
DROP TABLE TIPO_RECETA CASCADE CONSTRAINTS;
DROP TABLE RECETA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE DIRECCION CASCADE CONSTRAINTS;
DROP TABLE PACIENTE CASCADE CONSTRAINTS;

-- CASO 1 --
-- CREACION TABLA VIA ADMINISTRACION --
CREATE TABLE VIA_ADMIN
(
id_via NUMBER(3),
descripcion VARCHAR2(25) NOT NULL,
CONSTRAINT PK_VIA_ADMIN PRIMARY KEY (id_via)
);

-- CREACION TABLA TIPO MEDICAMENTO --
CREATE TABLE TIPO_MED
(
id_tipo NUMBER(2),
descripcion VARCHAR2(25) NOT NULL,
CONSTRAINT PK_TIPO_MED PRIMARY KEY (id_tipo)
);

-- CREACION TABLA DOSIS --
CREATE TABLE DOSIS
(
id_dosis NUMBER(5),
descripcion VARCHAR2(25) NOT NULL,
CONSTRAINT PK_DOSIS PRIMARY KEY (id_dosis)
);

-- CREACION TABLA MEDICAMENTO --
CREATE TABLE MEDICAMENTO        
(
cod_med NUMBER(7),
nombre VARCHAR2(25) NOT NULL,
stock NUMBER(3) NOT NULL,
VIA_ADMIN_id_via NUMBER(3) NOT NULL,
TIPO_MED_id_tipo NUMBER(2) NOT NULL,
DOSIS_id_dosis NUMBER(5) NOT NULL,
CONSTRAINT PK_MEDICAMENTO PRIMARY KEY (cod_med),
CONSTRAINT FK_MEDICAMENTO_VIA_ADMIN FOREIGN KEY (VIA_ADMIN_id_via) REFERENCES VIA_ADMIN (id_via),
CONSTRAINT FK_MEDICAMENTO_TIPO_MED FOREIGN KEY (TIPO_MED_id_tipo) REFERENCES TIPO_MED (id_tipo),
CONSTRAINT FK_MEDICAMENTO_DOSIS FOREIGN KEY (DOSIS_id_dosis) REFERENCES DOSIS (id_dosis)
);
-- CREACION TABLA ESPECIALIDAD --
CREATE TABLE ESPECIALIDAD
(
id_espe NUMBER(5) GENERATED ALWAYS AS IDENTITY,
nombre VARCHAR2(25) NOT NULL,
CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (id_espe)
);

-- CREACION TABLA MEDICO --
CREATE TABLE MEDICO
(
id_medico NUMBER(5),
rut NUMBER(8) NOT NULL,
dv_rut VARCHAR2(1) NOT NULL CHECK ( dv_rut IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K')),
pnombre VARCHAR2(25) NOT NULL,
snombre VARCHAR2(25),
papellido VARCHAR2(25) NOT NULL,
sapellido VARCHAR2(25),
telefono NUMBER(11) UNIQUE,
ESPECIALIDAD_id_espe NUMBER(5) NOT NULL,
CONSTRAINT PK_MEDICO PRIMARY KEY (id_medico),
CONSTRAINT FK_MEDICO_ESPECIALIDAD FOREIGN KEY(ESPECIALIDAD_id_espe) REFERENCES ESPECIALIDAD (id_espe)
);

-- CREACION TABLA DIGITADOR --
CREATE TABLE DIGITADOR
(
id_digit NUMBER(5),
rut NUMBER(8) NOT NULL,
dv_rut VARCHAR2(1) NOT NULL CHECK ( dv_rut IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K')),
pnombre VARCHAR2(25) NOT NULL,
papellido VARCHAR2(25) NOT NULL,
CONSTRAINT PK_DIGITADOR PRIMARY KEY (id_digit)
);

-- CREACION TABLA BANCO --
CREATE TABLE BANCO
(
cod_banco NUMBER(2),
nombre VARCHAR2(25) NOT NULL,
CONSTRAINT PK_BANCO PRIMARY KEY (cod_Banco)
);

-- CREACION TABLA METODO PAGO --
CREATE TABLE METODO_PAGO
(
id_met_p  NUMBER(4),
nombre VARCHAR2(25) NOT NULL,
BANCO_cod_banco NUMBER(2) NOT NULL,
CONSTRAINT PK_METODO_PAGO PRIMARY KEY (id_met_p),
CONSTRAINT FK_METODO_PAGO_BANCO FOREIGN KEY (BANCO_cod_banco) REFERENCES BANCO (cod_banco)
);

-- CREACION TABLA PAGO --
CREATE TABLE PAGO
(
cod_boleta NUMBER(6),
monto_total VARCHAR2(25) NOT NULL,
fecha_pago DATE NOT NULL,
METODO_PAGO_id_met_p NUMBER(4)NOT NULL,
CONSTRAINT PK_PAGO PRIMARY KEY (cod_boleta),
CONSTRAINT FK_PAGO_METODO_PAGO FOREIGN KEY (METODO_PAGO_id_met_p) REFERENCES METODO_PAGO (id_met_p)
);

--CREACION TABLA DIAGNOSTICO --
CREATE TABLE DIAGNOSTICO
(
cod_diag NUMBER(3),
nombre VARCHAR2(25) NOT NULL,
CONSTRAINT PK_DIAGNOSTICO PRIMARY KEY (cod_diag)
);

-- CREACION TABLA TIPO_RECETA --
CREATE TABLE TIPO_RECETA
(
id_t_rec NUMBER(3),
descripcion VARCHAR2(25) NOT NULL,
CONSTRAINT PK_TIPO_RECETA PRIMARY KEY (id_t_rec)
);

-- CREACION TABLA RECETA --
CREATE TABLE RECETA
(
cod_receta NUMBER(7),
observaciones VARCHAR2(500),
fecha_emision NUMBER(5) NOT NULL,
fecha_vencimiento VARCHAR2(25),
MEDICAMENTO_cod_med NUMBER(7) NOT NULL,
MEDICO_id_medico NUMBER(5) NOT NULL,
DIGITADOR_id_digit NUMBER(5) NOT NULL,
DIAGNOSTICO_cod_diag NUMBER(3) NOT NULL,
TIPO_RECETA_id_t_rec NUMBER(3) NOT NULL,
PAGO_cod_boleta NUMBER(6) NOT NULL,
CONSTRAINT PK_RECETA PRIMARY KEY (cod_Receta),
CONSTRAINT FK_RECETA_MEDICAMENTO FOREIGN KEY (MEDICAMENTO_cod_med) REFERENCES MEDICAMENTO (cod_med),
CONSTRAINT FK_RECETA_MEDICO FOREIGN KEY (MEDICO_id_medico) REFERENCES MEDICO (id_medico),
CONSTRAINT FK_RECETA_DIGITADOR FOREIGN KEY (DIGITADOR_id_digit) REFERENCES DIGITADOR (id_digit),
CONSTRAINT FK_RECETA_DIAGNOSTICO FOREIGN KEY (DIAGNOSTICO_cod_diag) REFERENCES DIAGNOSTICO (cod_diag),
CONSTRAINT FK_RECETA_TIPO_RECETA FOREIGN KEY (TIPO_RECETA_id_t_rec) REFERENCES TIPO_RECETA (id_t_rec),
CONSTRAINT FK_RECETA_PAGO FOREIGN KEY (PAGO_cod_boleta) REFERENCES PAGO (cod_boleta)
);

-- CREACION TABLA REGION --
CREATE TABLE REGION
(
id_region NUMBER(5),
nombre VARCHAR2(25) NOT NULL,
CONSTRAINT PK_REGION PRIMARY KEY (id_region)
);

-- CREACION TABLA CIUDAD --
CREATE TABLE CIUDAD
(
id_ciudad NUMBER(5),
nombre VARCHAR2(25) NOT NULL,
REGION_id_region NUMBER(5) NOT NULL,
CONSTRAINT PK_CIUDAD PRIMARY KEY (id_ciudad),
CONSTRAINT FK_CIUDAD_REGION FOREIGN KEY (REGION_id_region) REFERENCES REGION (id_region)
);

-- CREACION TABLA COMUNA --
CREATE TABLE COMUNA
(
id_comuna NUMBER(5) GENERATED ALWAYS AS IDENTITY (START WITH 1101 INCREMENT BY 1),
nombre VARCHAR2(25) NOT NULL,
CIUDAD_id_ciudad NUMBER(5) NOT NULL,
CONSTRAINT PK_COMUNA PRIMARY KEY (id_comuna),
CONSTRAINT FK_COMUNA_CIUDAD FOREIGN KEY (CIUDAD_id_ciudad) REFERENCES CIUDAD (id_ciudad)
);

-- CREACION TABLA DIRECCION --
CREATE TABLE DIRECCION
(
id_direccion NUMBER(5),
calle VARCHAR2(25) NOT NULL,
numeracion NUMBER(5) NOT NULL,
COMUNA_id_comuna NUMBER(5) NOT NULL,
CONSTRAINT PK_DIRECCION PRIMARY KEY (id_direccion),
CONSTRAINT FK_DIRECCION_COMUNA FOREIGN KEY (COMUNA_id_comuna) REFERENCES COMUNA (id_comuna)
);

-- CREACION TABLA PACIENTE --
CREATE TABLE PACIENTE
(
rut NUMBER(8),
dv_rut VARCHAR2(1) NOT NULL CHECK ( dv_rut IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'K')),
pnombre VARCHAR2(25) NOT NULL,
snombre VARCHAR2(25),
papellido VARCHAR2(25) NOT NULL,
sapellido VARCHAR2(25),
edad DATE NOT NULL,
telefono NUMBER(11) NOT NULL,
DIRECCION_id_direccion NUMBER(5) NOT NULL,
RECETA_cod_receta NUMBER(7) NOT NULL,
CONSTRAINT PK_PACIENTE PRIMARY KEY (rut),
CONSTRAINT FK_PACIENTE_DIRECCION FOREIGN KEY (DIRECCION_id_direccion) REFERENCES DIRECCION (id_direccion),
CONSTRAINT FK_PACIENTE_RECETA FOREIGN KEY (RECETA_cod_receta) REFERENCES RECETA (cod_receta)
);

-- CASO 2 --
-- PRECIOS UNITARIOS DE MEDICAMENTOS
ALTER TABLE MEDICAMENTO
ADD 
(
precio_unitario NUMBER(10,0)
CONSTRAINT chk_precio_unitario
CHECK (precio_unitario BETWEEN 1000 AND 2000000)
);

-- RESTRICCION METODOS DE PAGO
ALTER TABLE METODO_PAGO
ADD CONSTRAINT chk_metodo_pago 
CHECK (nombre IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA'));

-- REEMPLAZO EDAD POR FECHA DE NACIMIENTO PACIENTE --
ALTER TABLE PACIENTE DROP COLUMN edad;

ALTER TABLE PACIENTE
ADD (
fecha_nacimiento DATE NOT NULL
);